apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $clustername
  region: us-east-1
  version: 1.33.7
managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    # Optional: Enable SSH access to nodes
    # ssh:
    #   allow: true
    #   publicKeyPath: ~/.ssh/id_rsa.pub
    labels: { role: worker }
    tags:
      # Optional: Add custom tags to your nodes
      created-by: eksctl
