apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $CLUSTER_NAME
  region: $AWS_REGION
  version: $EKS_VERSION
managedNodeGroups:
  - name: managed-ng-1
    instanceType: $NODE_TYPE
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    # Optional: Enable SSH access to nodes
    # ssh:
    #   allow: true
    #   publicKeyPath: ~/.ssh/id_rsa.pub
    labels: { role: worker }
    tags:
      # Optional: Add custom tags to your nodes
      created-by: eksctl
