global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
      system:
        name: "spire-system"
      server:
        name: "spire-server"
    ingressControllerType: ""
    clusterName: $CLUSTER_NAME
    trustDomain: example.org
    caSubject:
      country: ARPA
      organization: Example
      commonName: example.org
