global:
  spire:
    trustDomain: example.org
spire-agent:
    authorizedDelegates:
        - "spiffe://example.org/ns/istio-system/sa/ztunnel"
    sockets:
        admin:
            enabled: true
            mountOnHost: true
        hostBasePath: /run/spire/agent/sockets
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
spire-server:
  upstreamAuthority:
    disk:
      enabled: true
      secret:
        create: false
        name: spiffe-upstream-ca
spiffe-csi-driver:
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists